apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/froissant/pokedex:main
  newName: ghcr.io/froissant/pokedex
  newTag: sha-7b0b2ef
